services:
    strelaysrv:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: strelaysrv
        restart: always
        volumes:
            - strelaysrv:/keys
        command:
            - "-global-rate=5000000"
            # - "-provided-by=ImranR.DEV"
        ports:
            - 22067:22067
            - 22070:22070

volumes:
    strelaysrv: {}
